spring.application.name=erp
# 1. Cấu hình kết nối MySQL (Thay đổi tên db 'erp_db' theo ý bạn)
spring.datasource.url=jdbc:mysql://localhost:3306/erp_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# 2. Định danh Dialect cho Hibernate (Khắc phục trực tiếp lỗi của bạn)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Tự động cập nhật bảng dữ liệu từ Code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true